---

# Remark that common variables are defined in `group_vars/all.yml`

- name: Primary/Secondary with Shared Inventory
  hosts: dns
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  tasks:
    - name: Include bind
      include_role:
        name: ckaserer.bind
...
